helpDesk/Controllers/ComplainController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using helpDesk.Entity;

namespace helpDesc.Controllers
{
    [Authorize]
    public class ComplainController : Controller
    {
        private helpDescEntities db = new helpDescEntities();
        public ActionResult Index()
        {
            return View();
        }
        // Showing the details of complain and status can be changed by user based roles 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Complain complain = db.Complains.Find(id);
            if (complain == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (!User.IsInRole("Admin"))
                if (complain.org_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (complain == null)
            {
                return HttpNotFound();
            }
            ViewBag.statusList = new SelectList(db.Status.Where(r => r.is_client == "0").ToList(), "id", "status_value", 2);

            return View(complain);
        }
        public ActionResult DetailsStatus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Complain complain = db.Complains.Find(id);
            if (complain == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return PartialView("", db.ComplainStatus.Where(r => r.complain_id == id).ToList());
        }
        public ActionResult Create()
        {
            var org_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation;
            ViewBag.complain_type_id = new SelectList(db.ComplainTypes, "id", "complainType1");
            ViewBag.system_id = new SelectList(db.SystemModules.Where(r => r.is_module == false).Where(r => r.organisation_id == org_id).Where(r => r.is_enabled == true), "id", "name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Subadmin, Moderator, Superadmin, Admin")]
        public ActionResult Create([Bind(Include = "id,complain_date,system_id,complain_text,complain_type_id,status_id")] Complain complain, HttpPostedFileBase file, int module_id = 0)
        {
            if (ModelState.IsValid && module_id != 0 && complain.complain_text != null && complain.complain_text != "")
            {
                complain.system_id = module_id;
                complain.inserted_date = DateTime.Now;
                complain.user_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id;
                complain.status_id = 5;
                complain.is_delete = false;
                Guid guid = Guid.NewGuid();
                if (UploadImages(file, guid) == true)
                {
                    complain.document_name = file.FileName;
                    complain.document_url = guid + file.FileName;
                }
                complain.org_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation;
                db.Complains.Add(complain);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.user_id = new SelectList(db.AspNetUsers, "Id", "UserName", complain.user_id);
            ViewBag.complain_type_id = new SelectList(db.ComplainTypes, "id", "complainType1", complain.complain_type_id);
            ViewBag.org_id = new SelectList(db.Organisations, "id", "org_name", complain.org_id);
            ViewBag.status_id = new SelectList(db.Status, "id", "status_value", complain.status_id);
            ViewBag.system_id = new SelectList(db.SystemModules.Where(r => r.is_module == false), "id", "name", complain.system_id);
            return View(complain);
        }
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Complain complain = db.Complains.Find(id);

            if (complain.org_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ViewBag.currentUser = "";
            if (complain.user_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id)
                ViewBag.currentUser = complain.AspNetUser.UserName;

            if (complain.status_id != 5)
                return RedirectToAction("Details", new { id = id });
            if (!User.IsInRole("Admin"))
                if (complain.org_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (complain == null)
            {
                return HttpNotFound();
            }
            ViewBag.module_id = new SelectList(db.SystemModules.Where(r => r.parent_id == complain.SystemModule.parent_id), "id", "name", complain.system_id);
            ViewBag.user_id = new SelectList(db.AspNetUsers, "Id", "UserName", complain.user_id);
            ViewBag.complain_type_id = new SelectList(db.ComplainTypes, "id", "complainType1", complain.complain_type_id);
            ViewBag.org_id = new SelectList(db.Organisations, "id", "org_name", complain.org_id);
            ViewBag.status_id = new SelectList(db.Status, "id", "status_value", complain.status_id);
            ViewBag.system_id = new SelectList(db.SystemModules.Where(r => r.is_module == false), "id", "name", complain.SystemModule.parent_id);
            return View(complain);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,complain_text,system_id,complain_type_id")] Complain complain, int module_id, HttpPostedFileBase file)
        {
            var item = db.Complains.Find(complain.id);
            if (item.org_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (item.user_id != db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (ModelState.IsValid)
            {
                Guid guid = Guid.NewGuid();
                if (file != null)
                    if (item.document_url != null)
                    {
                        var path = Path.Combine(Server.MapPath("/Content/file/"), complain.document_url);
                        FileInfo fileDelete = new FileInfo(path);
                        if (fileDelete.Exists)
                            fileDelete.Delete();
                        item.document_url = null;
                        item.document_name = null;
                    }

                if (UploadImages(file, guid) == true)
                {
                    item.document_name = file.FileName;
                    item.document_url = guid + file.FileName;
                }
                item.system_id = module_id;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.user_id = new SelectList(db.AspNetUsers, "Id", "UserName", complain.user_id);
            ViewBag.complain_type_id = new SelectList(db.ComplainTypes, "id", "complainType1", complain.complain_type_id);
            ViewBag.org_id = new SelectList(db.Organisations, "id", "org_name", complain.org_id);
            ViewBag.status_id = new SelectList(db.Status, "id", "status_value", complain.status_id);
            ViewBag.system_id = new SelectList(db.SystemModules.Where(r => r.is_module == false), "id", "name", complain.system_id);


            return View(complain);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Complain complain = db.Complains.Find(id);
            if (complain == null)
            {
                return HttpNotFound();
            }
            return View(complain);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public ActionResult ModuleList(int id)
        {
            var org_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation;

            ViewBag.module_id = new SelectList(db.SystemModules.Where(r => r.parent_id == id).Where(r => r.organisation_id == org_id).Where(r => r.is_enabled == true), "id", "name");
            return PartialView("ModuleList");
        }
        public bool UploadImages(HttpPostedFileBase file, Guid guid)
        {
            if (file != null)
            {
                int isFileExist = 0;
                try
                {
                    if (file != null || file.ContentLength > 0)
                        isFileExist = 1;
                }
                catch { isFileExist = 0; return false; }
                // file iin extension shalgah
                if (isFileExist == 1)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg" || Path.GetExtension(file.FileName).ToLower() == ".png"

helpDesk/Controllers/TutorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace helpDesk.Controllers
{
    public class TutorialController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

helpDesk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div id="followingBallsG" style="display: none; position: fixed; margin-top: 100px; width: 200px; left: 50%; margin-left: -100px">
                <div id="followingBallsG_1" class="followingBallsG">
                </div>
                <div id="followingBallsG_2" class="followingBallsG">
                </div>
                <div id="followingBallsG_3" class="followingBallsG">
                </div>
                <div id="followingBallsG_4" class="followingBallsG">
                </div>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Newsonic", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("QAAsk") || User.IsInRole("QAAnswer") || User.IsInRole("Superadmin"))
                    {
                        string QA = "";
                        if (User.IsInRole("Superadmin"))
                        {
                            QA = "QA(" + helpDesk.Controllers.OrganisationController.NewComplainCount() + ")";
                        }
                        else
                        {
                            QA = "QA";
                        }
                        <li>@Html.ActionLink(QA, "Index", "QA")</li>
                        if (User.IsInRole("QAAdmin") || User.IsInRole("QAAsk"))
                        {
                        <li>@Html.ActionLink("QA Нэмэх", "Create", "QA")</li>
                        }
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            @if (User.IsInRole("Superadmin"))
                            {
                                string huseld = "Хүсэлт(" + helpDesk.Controllers.OrganisationController.NewComplainCount() + ")";
                                @Html.ActionLink(huseld, "Index", "Complain")
                            }
                            else
                            {
                                @Html.ActionLink("Хүсэлт", "Index", "Complain")
                            }
                        </li>
                        <li>@Html.ActionLink("Хүсэлт оруулах", "Create", "Complain")</li>
                    }
                    @if (User.IsInRole("Superadmin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Админ <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/Admin">Админы хэсэг</a></li>
                                <li><a href="/Admin/Admins">Админ хэрэглэгч</a></li>
                                <li><a href="/Admin/Organisation">Бүртгэлтэй байгууллага</a></li>
                                <li><a href="/Admin/System">Систем, төрөл оруулах</a></li>
                                <li class="divider"></li>
                                <li><a href="/Report">Тайлан</a></li>
                            </ul>
                        </li>
                    }
                    <li>@Html.ActionLink("Заавар", "Index", "Tutorial")</li>
                    @if (User.IsInRole("Subadmin"))
                    {
                        string link = helpDesk.Controllers.OrganisationController.OrganisationName(User.Identity.Name);

                        <li>@Html.ActionLink(link, "Index", "Organisation")</li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - "НЬЮСОНИК ХХК"-ны өмч</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>