helpDesk/Controllers/QAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using helpDesk.Entity;

namespace helpDesk.Controllers
{
    public class QAController : Controller
    {
        private helpDescEntities db = new helpDescEntities();
        [Authorize(Roles = "QAAsk, QAAnswer, QAAdmin")]
        public ActionResult Index()
        {
            var qas = db.QAs.Include(q => q.AspNetUser).Include(q => q.AspNetUser1).OrderByDescending(r => r.id);
            return View(qas.ToList());
        }
        [Authorize(Roles = "QAAsk, QAAnswer, QAAdmin")]
        public ActionResult QAList(string value = "", int page = 1)
        {
            int skip = (page - 1) * 4;
            int take = 4;
            if (value == "")
            {
                if (User.IsInRole("Superadmin"))
                {
                    var QAs = db.QAs.Include(c => c.AspNetUser).Include(c => c.Organisation);
                    ViewBag.maxSize = QAs.Count();
                    return PartialView("QAList", QAs.OrderByDescending(r => r.id).Skip(skip).Take(take).ToList());
                }
                else
                {
                    int org_id = (int)db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation;
                    var complains = db.QAs.Include(c => c.AspNetUser).Include(c => c.Organisation).Where(r => r.org_id == org_id);
                    ViewBag.maxSize = complains.Count();
                    return PartialView("QAList", complains.OrderByDescending(r => r.id).Skip(skip).Take(take).ToList());
                }
            }
            else
            {
                if (User.IsInRole("Superadmin"))
                {
                    var list = db.QAs.Where(r => r.question.Contains(value) || r.AspNetUser.UserName.Contains(value) || r.answer.Contains(value) || r.Organisation.org_name.Contains(value));
                    ViewBag.maxSize = list.Count();
                    return PartialView("QAList", list.OrderByDescending(r => r.id).Skip(skip).Take(take).ToList());
                }
                else
                {
                    int org_id = (int)db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).organisation;
                    var list = db.QAs.Where(r => r.question.Contains(value) || r.AspNetUser.UserName.Contains(value) || r.answer.Contains(value) ||
                        r.Organisation.org_name.Contains(value)).Where(r => r.org_id == org_id);
                    ViewBag.maxSize = list.Count();
                    return PartialView("QAList", list.ToList());
                }
            }
        }
        [Authorize(Roles = "QAAsk, QAAnswer, QAAdmin")]
        public ActionResult Create()
        {
            if (User.IsInRole("Superadmin"))
                ViewBag.org_id = new SelectList(db.Organisations, "id", "org_name");
            else
                ViewBag.org_id = new SelectList(db.Organisations.Where(r => r.id == 1), "id", "org_name");

            return View();
        }
        [HttpPost]
        [Authorize(Roles = "QAAsk, QAAdmin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "question,question_file,org_id")] QA qa, HttpPostedFileBase question_file)
        {
            if (ModelState.IsValid && qa.question != null && qa.org_id != null)
            {
                qa.ask_date = DateTime.Now;
                qa.question_user_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id;
                db.QAs.Add(qa);
                Guid guid = Guid.NewGuid();
                if (UploadImages(question_file, guid) == true)
                {
                    qa.question_file = guid + question_file.FileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.org_id = new SelectList(db.Organisations, "id", "org_name");
            return View(qa);
        }
        [Authorize(Roles = "QAAsk, QAAdmin")]
        public ActionResult Question(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QA qa = db.QAs.Find(id);
            if (qa == null)
            {
                return HttpNotFound();
            }
            return View(qa);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "QAAsk, QAAdmin")]
        public ActionResult Question([Bind(Include = "id,question,question_file")] QA qa, HttpPostedFileBase question_file)
        {
            if (ModelState.IsValid)
            {
                var item = db.QAs.Find(qa.id);
                item.ask_date = DateTime.Now;
                item.question = qa.question;
                item.question_user_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id;
                db.Entry(item).State = EntityState.Modified;
                Guid guid = Guid.NewGuid();
                if (UploadImages(question_file, guid) == true)
                {
                    item.question_file = guid + question_file.FileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(qa);
        }
        [Authorize(Roles = "QAAnswer, QAAdmin")]
        public ActionResult Answer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QA qa = db.QAs.Find(id);


            if (qa == null || qa.answer_date > DateTime.Now.AddDays(-2))
            {
                return RedirectToAction("Index");
            }
            return View(qa);
        }
        [HttpPost]
        [Authorize(Roles = "QAAnswer, QAAdmin")]
        [ValidateAntiForgeryToken]
        public ActionResult Answer([Bind(Include = "id,answer,answer_file")] QA qa, HttpPostedFileBase answer_file)
        {
            if (ModelState.IsValid && qa.answer != "" && qa.answer != null)
            {
                var item = db.QAs.Find(qa.id);
                item.answer_date = DateTime.Now;
                item.answer = qa.answer;
                item.answer_user_id = db.AspNetUsers.Single(r => r.UserName == User.Identity.Name).Id;
                db.Entry(item).State = EntityState.Modified;
                Guid guid = Guid.NewGuid();
                if (UploadImages(answer_file, guid) == true)
                {
                    item.answer_file = guid + answer_file.FileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(qa);
        }
        [Authorize(Roles = "QAAdmin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QA qa = db.QAs.Find(id);
            if (qa == null)
            {
                return HttpNotFound();
            }
            return View(qa);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "QAAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            QA qa = db.QAs.Find(id);
            db.QAs.Remove(qa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public bool UploadImages(HttpPostedFileBase file, Guid guid)
        {
            if (file != null)
            {
                int isFileExist = 0;
                try
                {
                    if (file != null || file.ContentLength > 0)
                        isFileExist = 1;
                }
                catch { isFileExist = 0; return false; }
                // file iin extension shalgah
                if (isFileExist == 1)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg" || Path.GetExtension(file.FileName).ToLower() == ".png"
                        || Path.GetExtension(file.FileName).ToLower() == ".gif" || Path.GetExtension(file.FileName).ToLower() == ".jpeg"
                        || Path.GetExtension(file.FileName).ToLower() == ".docx" || Path.GetExtension(file.FileName).ToLower() == ".doc"
                        || Path.GetExtension(file.FileName).ToLower() == ".pdf"
                        )
                    {
                        isFileExist = 1;
                    }
                    else isFileExist = 0;
                }
                else return false;

                if (isFileExist == 1)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    file.SaveAs(Server.MapPath("~/Content/file/" + guid + fileName));
                }
                else return false;
                return true;
            }
            return false;
        }
        [HttpPost]
        [Authorize(Roles = "QAask, QAAdmin")]
        public ActionResult DeleteAttachedFileQuestion(int fileid, string url)
        {
            var item = db.QAs.Find(fileid);
            if (item.question_file == url)
            {
                var path = Path.Combine(Server.MapPath("/Content/file/"), item.question_file);
                FileInfo file = new FileInfo(path);
                if (file.Exists)
                    file.Delete();
                item.question_file = null;
                db.SaveChanges();
            }
            return RedirectToAction("Question", new { id = fileid });

        }
        [HttpPost]
        [Authorize(Roles = "QAAnswer, QAAdmin")]

helpDesk/Views/QA/Answer.cshtml
@model helpDesk.Entity.QA
@{
    ViewBag.Title = "Хариулах";
}
<h2>Хариулах</h2>

@if (Model.answer_user_id == null)
{ 
    using (Html.BeginForm("Answer", "QA", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>QA</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.id)
            <div class="form-group">
                @Html.LabelFor(model => model.answer, "Хариулт", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer, new { style = "height:200px;width:100%" })
                    @Html.ValidationMessageFor(model => model.answer)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.answer_file, "Файл хавсаргах", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="answer_file" class="form-control" id="answer_file" />
                    <label>10mb-с доош зураг, pdf, doc, docx өргөтгөлтэй файлыг хавсаргаж болно.</label>
                    @Html.ValidationMessageFor(model => model.answer_file)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Хариулт хадгалах" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}
else if (User.Identity.Name == Model.AspNetUser.UserName)
{

    using (Html.BeginForm("Answer", "QA", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>QA</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.id)
            <div class="form-group">
                @Html.LabelFor(model => model.answer, "Хариулт", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.answer, new { style = "height:200px;width:100%" })
                    @Html.ValidationMessageFor(model => model.answer)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.answer_file, "Файл хавсаргах", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="answer_file" class="form-control" id="answer_file" />
                    <label>10mb-с доош зураг, pdf, doc, docx өргөтгөлтэй файлыг хавсаргаж болно.</label>
                    @Html.ValidationMessageFor(model => model.answer_file)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Хариулт хадгалах" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    if (Model.answer_file != null)
    {
        <form action="/QA/DeleteAttachedFileAnswer" method="post">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-10">
                        <a href="@("/Content/file/" + Model.answer_file)" class="btn btn-default btn-sm">Харах</a>
                        <input type="hidden" name="fileid" value="@Model.id" />
                        <input type="hidden" name="url" value="@Model.answer_file" />
                        <input type="submit" value="Хавсаргасан файл устгах" class="btn btn-danger btn-sm" />
                    </div>
                </div>
            </div>
        </form>
    }
}
else { 
     <span class="label label-warning"> Зөвхөн оруулсан хэрэглэгч л засах боломжтой </span>
}

<div>
    @Html.ActionLink("Жагсаалтруу буцах", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

helpDesk/Views/QA/Create.cshtml
@model helpDesk.Entity.QA

@{
    ViewBag.Title = "Асуулт оруулах";
}

<h2>Асуулт оруулах</h2>


@using (Html.BeginForm("Create", "QA", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QA</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.question, "Асуулт асуух", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.question, new { style="height:200px;width:100%"})
                @Html.ValidationMessageFor(model => model.question)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.question_file, "Файл хавсаргах", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="question_file" class="form-control" id="question_file" />
                <label>10mb-с доош зураг, pdf, doc, docx өргөтгөлтэй файлыг хавсаргаж болно.</label>
                @Html.ValidationMessageFor(model => model.question_file)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.org_id, "Асуулт асуух байгууллага",new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownList("org_id", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Асуулт оруулах" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Жагсаалтруу буцах", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

helpDesk/Views/QA/Delete.cshtml
@model helpDesk.Entity.QA

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ask_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ask_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser1.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser1.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

helpDesk/Views/QA/Details.cshtml
@model helpDesk.Entity.QA

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>QA</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ask_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ask_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser1.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser1.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

helpDesk/Views/QA/Edit.cshtml
@model helpDesk.Entity.QA

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QA</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.question, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question)
                @Html.ValidationMessageFor(model => model.question)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer)
                @Html.ValidationMessageFor(model => model.answer)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ask_date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ask_date)
                @Html.ValidationMessageFor(model => model.ask_date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer_date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer_date)
                @Html.ValidationMessageFor(model => model.answer_date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer_user_id, "answer_user_id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("answer_user_id", String.Empty)
                @Html.ValidationMessageFor(model => model.answer_user_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question_user_id, "question_user_id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("question_user_id", String.Empty)
                @Html.ValidationMessageFor(model => model.question_user_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question_file, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question_file)
                @Html.ValidationMessageFor(model => model.question_file)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer_file, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer_file)
                @Html.ValidationMessageFor(model => model.answer_file)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

helpDesk/Views/QA/Index.cshtml
@{
    ViewBag.Title = "Асуултууд";
}

   
<h2 style="float:left">Асуултын жагсаалт</h2>
<br />
<input style="float:right" type="text" id="search-value" onkeyup="SearchBoxAdd($(this).val())" class="form-control input-sm" placeholder="Хайх үгээ бичээд хай" />

<br />
<br />
<div id="complain-list">
    @Html.Action("QAList")
</div>

<script type="text/javascript">
    function SearchBoxAdd(sval) {
        if (sval !== "") {
            $("#followingBallsG").show();
            $.ajax({
                type: "POST",
                url: "/QA/QAList",
                cache: false,
                data: { value: sval },
                success: function (result) {
                    $("#complain-list").html(result);
                    $("#followingBallsG").hide();
                }
            });
        } else {
            $.ajax({
                type: "POST",
                url: "/QA/QAList",
                cache: false,
                success: function (result) {
                    $("#followingBallsG").hide();
                    $("#complain-list").html(result);
                }
            });
        }
    }
    function showPage(num) {
        var value = $("#search-value").val();
        $.ajax({
            type: "POST",
            url: "/QA/QAList",
            cache: false,
            data: { value: value, page: num },
            success: function (result) {
                $("#followingBallsG").hide();
                $("#complain-list").html(result);
            }
        });
    }
</script>

helpDesk/Views/QA/QAList.cshtml
@model IEnumerable<helpDesk.Entity.QA>

<table class="table table-bordered">
    <tr>
        <th>
            Асуулт
        </th>
        <th>
            Хариулт
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="width:50%;">
                <div>
                    @Html.DisplayFor(modelItem => item.question)
                </div>
                <br />
                <div>
                    <div style="float:left">
                        <div>

                            <label class="glyphicon glyphicon-time"></label> <strong> @Html.DisplayFor(modelItem => item.ask_date)</strong>
                        </div>
                        <div>

                            <label class="glyphicon glyphicon-file"></label> 
                            @if (item.question_file != null)
                                                                              {
                                <a href="@("Content/file/" + item.question_file)">Харах</a>
                                                                              }
                        </div>
                    </div>
                    <div style="float:right">
                        <div>
                            <label class="glyphicon glyphicon-user"></label>  <strong>  @Html.DisplayFor(modelItem => item.AspNetUser1.UserName)</strong>
                        </div>
                        <div>
                            <label class="glyphicon glyphicon-globe"></label>
                            <span class="label label-primary">@item.Organisation.org_name</span>
                            <a href="/QA/Question/@item.id">Засах</a>
                            <strong>№: @item.id</strong>
                        </div>
                    </div>
                </div>
                <div>
                </div>

            </td>
            <td style="width:50%;">
                @if (item.answer == null)
                {
                     <span class="label label-primary">@item.Organisation.org_name</span><span> хариулна</span><br />
                    if (helpDesk.Controllers.OrganisationController.isInCompanyUser(item.Organisation.id, User.Identity.Name) == 1)
                    { 
                        <a href="/QA/Answer/@item.id">Асуултанд хариулах</a>
                    }
                }
                else
                {
                    <div>
                        @Html.DisplayFor(modelItem => item.answer)
                    </div>
                    <br />
                    <div>
                        <label class="glyphicon glyphicon-time"></label><strong> @Html.DisplayFor(modelItem => item.answer_date)</strong>
                        Хариулт оруулсан: <strong>  @Html.DisplayFor(modelItem => item.AspNetUser.UserName)</strong>
                    </div>
                    <div style="float:left">
                        <label class="glyphicon glyphicon-file"></label> @if (item.answer_file != null)
                                                                         {
                            <a href="@("Content/file/" + item.answer_file)">Харах</a>
                                                                         }
                    </div>
                    <div style="float:right">
                        @if (helpDesk.Controllers.QAController.IsInRoleUserQA(item.answer_user_id, User.Identity.Name))
                        {
                            if (item.answer_date == null || ((DateTime)item.answer_date) > DateTime.Now.AddDays(-2))
                            { 
                                <a href="/QA/Answer/@item.id">Засах</a>
                            }
                        }
                    </div>
                }
            </td>
        </tr>
    }

</table>
@{int page = 1;}
<ul class="pagination pagination-sm">
    <li class="disabled"><a href="#">«</a></li>
    @for (int i = 0; i <= ((int)ViewBag.maxSize) / 4; i++)
    {
        <li><a href="javascript:showPage('@(i + 1)')">@(page++)</a></li>
    }
    <li><a href="#">»</a></li>
</ul>

helpDesk/Views/QA/Question.cshtml
@model helpDesk.Entity.QA
@{
    ViewBag.Title = "Асуулт засах";
}
<h2>Асуулт засах</h2>

@using (Html.BeginForm("Question", "QA", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QA</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.question, "Асуулт", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.question, new { style = "height:200px;width:100%" })
                @Html.ValidationMessageFor(model => model.question)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.question_file, "Файл хавсаргах", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="question_file" class="form-control" id="question_file" />
                <label>10mb-с доош зураг, pdf, doc, docx өргөтгөлтэй файлыг хавсаргаж болно.</label>
                @Html.ValidationMessageFor(model => model.question_file)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Хариулт хадгалах" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (Model.question_file != null)
{
    <form action="/QA/DeleteAttachedFileQuestion" method="post">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-10">
                    <a href="@("/Content/file/" + Model.question_file)" class="btn btn-default btn-sm">Харах</a>
                    <input type="hidden" name="fileid" value="@Model.id" />
                    <input type="hidden" name="url" value="@Model.question_file" />
                    <input type="submit" value="Хавсаргасан файл устгах" class="btn btn-danger btn-sm" />
                </div>
            </div>
        </div>
    </form>
}

<div>
    @Html.ActionLink("Жагсаалтруу буцах", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}